#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift File.expand_path("../lib", __dir__)
require "mailmate"
require "mailmate/cli/mailboxes"

require "mailmate/cli/version_flag"

Mailmate::CLI::VersionFlag.handle!(ARGV, "mm-mailboxes")

exit Mailmate::CLI::Mailboxes.run(ARGV)
